<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite parallel="tests" name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <listeners>
    <listener class-name="qa.inetbanking.qa.Extentlisteners.ExtentReporterNG"/>
  </listeners>
  <test thread-count="5" parallel="tests" name="Three Test(failed)">
    <classes>
      <class name="com.inetbankingNew.qa.testcases.ThreeTest">
        <methods>
          <include name="Threetest"/>
        </methods>
      </class> <!-- com.inetbankingNew.qa.testcases.ThreeTest -->
    </classes>
  </test> <!-- Three Test(failed) -->
  <test thread-count="5" parallel="tests" name="Test(failed)">
    <classes>
      <class name="com.inetbankingNew.qa.testcases.LoginTest">
        <methods>
          <include name="setup"/>
          <include name="teardown"/>
          <include name="logintest" invocation-numbers="0 1"/>
        </methods>
      </class> <!-- com.inetbankingNew.qa.testcases.LoginTest -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
